Repository Three-Points/LaRifamos-Backend, pull requests merged in 2022-10, with the labels that each got.

#7 Feat management model
  package-lock.json
  package.json
  prisma/migrations/20220928043732_enum_management_permission/migration.sql
  prisma/migrations/20220928043732_model_management/migration.sql
  prisma/schema.prisma
  src/db/mocks/management.mock.js
  src/db/models/management.prisma
  src/db/seeds/dev.seed.js
Labels: Feature

#8 Initial Database
  doppler.yml
  package-lock.json
  package.json
  prisma/migrations/20220927030949_model_product/migration.sql
  prisma/migrations/20220927031141_enum_product_state/migration.sql
  prisma/migrations/20220927031240_relation_product_image/migration.sql
  prisma/migrations/20220927031359_model_raffle/migration.sql
  prisma/migrations/20220927031504_enum_raffle_state/migration.sql
  prisma/migrations/20220927031617_enum_raffle_type/migration.sql
  prisma/migrations/20220927031718_enum_raffle_category/migration.sql
  prisma/migrations/20220927031842_relation_product_raffle/migration.sql
  prisma/migrations/20220928043732_enum_management_permission/migration.sql
  prisma/migrations/20220928043732_model_management/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/db/mocks/management.mock.js
  src/db/mocks/products.mock.js
  src/db/mocks/raffles.mock.js
  src/db/models/management.prisma
  src/db/models/product.prisma
  src/db/models/raffle.prisma
  src/db/seeds/dev.seed.js
  src/db/seeds/index.seed.js
Labels: Alpha

#13 Update Database with Account and Ticket Models
  package-lock.json
  package.json
  prisma/migrations/20221019202404_model_account/migration.sql
  prisma/migrations/20221019202629_enum_role/migration.sql
  prisma/migrations/20221019205640_relation_account_raffle/migration.sql
  prisma/migrations/20221019224956_model_ticket/migration.sql
  prisma/migrations/20221019225415_relation_account_ticket/migration.sql
  prisma/migrations/20221019225505_relation_raffle_ticket/migration.sql
  prisma/schema.prisma
  src/db/mocks/accounts.mock.js
  src/db/mocks/tickets.mock.js
  src/db/models/account.prisma
  src/db/models/ticket.prisma
  src/db/seeds/dev.seed.js
Labels: Minor

#12 Raffles
  project/markdown/CHANGELOG.md
  src/controllers/ErrorServer.controller.js
  src/controllers/Raffle.controller.js
  src/models/Raffle.model.js
  test/controllers/errorServer.controller.test.js
  test/controllers/raffle/raffle.controller.test.js
  test/controllers/raffle/raffle.expect.js
  test/controllers/raffle/raffle.mock.ts
  test/libs/Prisma.test.js
Labels: Minor

#16 Remove Enum of Database
  prisma/migrations/20220927031141_enum_product_state/migration.sql
  prisma/migrations/20220927031504_enum_raffle_state/migration.sql
  prisma/migrations/20220927031617_enum_raffle_type/migration.sql
  prisma/migrations/20220927031718_enum_raffle_category/migration.sql
  prisma/migrations/20220928043732_enum_management_permission/migration.sql
  prisma/migrations/20220928043732_model_management/migration.sql
  prisma/migrations/20221019202404_model_account/migration.sql
  prisma/migrations/20221019202629_enum_role/migration.sql
  prisma/schema.prisma
  project/markdown/CHANGELOG.md
  src/db/models/account.prisma
  src/db/models/management.prisma
  src/db/models/product.prisma
  src/db/models/raffle.prisma
Labels: Minor, Fix

#17 Like/Shared A Raffle
  src/controllers/Account.controller.js
  src/libs/Prisma.js
  src/models/Account.model.js
  src/models/Raffle.model.js
  test/controllers/account/account.controller.test.js
  test/controllers/account/account.expect.js
  test/controllers/account/account.mock.js
  test/controllers/raffle/raffle.controller.test.js
  test/controllers/raffle/raffle.expect.js
  test/controllers/raffle/raffle.mock.js
  test/libs/Prisma.test.js
  test/models/account.model.test.js
  test/models/raffle.model.test.js
Labels: Minor

#22 Get a Raffle by ID
  src/controllers/Raffle.controller.js
  src/models/Raffle.model.js
  src/routes/raffle.route.js
  src/services/raffle.service.js
  test/controllers/raffle/raffle.controller.test.js
Labels: Feature
